services:
  db:
    image: postgres:17
    container_name: ddb_pg17
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data

    # Container resource caps
    cpus: "8.0"
    mem_limit: "32g"

    # Exec-form command: each argument is its own list item
    command:
      - postgres
      - -c
      - shared_buffers=8GB                 # ~25% of container RAM
      - -c
      - effective_cache_size=24GB          # OS cache hint (mem - shared_buffers)
      - -c
      - work_mem=256MB                     # per sort/hash; careful with concurrency
      - -c
      - maintenance_work_mem=2GB           # faster index builds, VACUUM, etc.
      - -c
      - max_parallel_workers_per_gather=0
      - -c
      - max_parallel_workers=0
      - -c
      - max_worker_processes=0
      - -c
      - max_parallel_maintenance_workers=0
      - -c
      - jit=off                            # less noise in microbenchmarks
      - -c
      - random_page_cost=1.1               # SSD/NVMe hint
      - -c
      - effective_io_concurrency=200       # SSD/NVMe hint
      - -c
      - checkpoint_timeout=30min           # fewer checkpoints
      - -c
      - checkpoint_completion_target=0.9
      - -c
      - wal_compression=on
      - -c
      - synchronous_commit=off             # helps inserts; no effect on SELECTs

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  pgdata:
